### ISSUE TITLE
follow plugin API

### ISSUE THREAD

**Issue by lucasduffey** [cah011/binja-avr#1]
https://github.com/Vector35/binaryninja-plugins/tree/master/plugins/official/sample_plugin

create plugin.json: https://github.com/cah011/binja-avr/pull/3
```__init__.py```: https://github.com/cah011/binja-avr/pull/2

**Comment by lucasduffey** [comment]
create plugin.json: https://github.com/cah011/binja-avr/pull/3
```__init__.py``: https://github.com/cah011/binja-avr/pull/2

**Comment by lucasduffey** [comment]
instructions for installing on linux (before plugin system is implemented)
```
cd ~/.binaryninja/plugins
git pull https://github.com/cah011/binja-avr binja_avr
echo "import binja_avr" >> wrapper.py
```

**Comment by lucasduffey** [comment]
when it's following plugin spec make an issue @ https://github.com/Vector35/binaryninja-plugins/issues

**Comment by cah011** [comment]
Everything should be fixed and correctly submitted as an issue and pull request.

**Comment by lucasduffey** [comment]
relevent pull request: https://github.com/Vector35/binaryninja-plugins/pull/9
