### ISSUE TITLE
need to use BranchType enum for dev api

### ISSUE THREAD

**Issue by lucasduffey** [cah011/binja-avr#7]
crash when I try to create a function of arch type AVR

```
/home/user/.binaryninja/repositories/plugin_status.json doesn't exist
Loaded Python plugin 'binja-avr'
Analysis update took 0.006 seconds

Types for platform AVR failed to load: error: file '/home/user/binaryninja/types/platform/___.c' not found
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/user/binaryninja/plugins/../python/binaryninja/architecture.py", line 439, in _get_instruction_info
  File "/home/user/.binaryninja/plugins/binja-avr/__init__.py", line 1098, in perform_get_instruction_info
    result.add_branch(CallDestination, addr + dst*2 + 1*2)
NameError: global name 'CallDestination' is not defined
Analysis update took 0.003 seconds

```

**Comment by lucasduffey** [comment]
return types are now BranchType.return_type

**Examples:**
* BranchType.FunctionReturn
* BranchType.CallDestination
* BranchType.CallDestination
* BranchType.UnconditionalBranch
* BranchType.TrueBranch
* BranchType.FalseBranch

**Comment by lucasduffey** [comment]
**Other changes**
* TextToken => InstructionTextTokenType.TextToken

**Comment by lucasduffey** [comment]
I'm not sure if this applies to stable, so I'm not going to submit pull request yet

**Comment by marcograss** [comment]
I think you can submit now, stable requires those changes also (I also made them but since there is already the issue..)
