### ISSUE TITLE
perform_get_instruction_info - src value undefined

### ISSUE THREAD

**Issue by lucasduffey** [cah011/binja-avr#9]
In the `perform_get_instruction_info` function I'm getting "src is undefined"

```
elif (instr == 'brbs' or instr == 'brbc'):
	result.add_branch(BranchType.TrueBranch, addr + src*2 + 1*2)
	result.add_branch(BranchType.FalseBranch, addr + 1*2)
```

I assumed it might be `src_value` instead, but I get another error when I replace `src` with `src_value`

**Comment by lucasduffey** [comment]
maybe it should be `dst`?

**Comment by cah011** [comment]
Indeed this is the case, merged. f293f49
